# Code of Conduct {#code}

## Safe and Professional

In addition to the general expectations laid out above, I am dedicated to making our lab a safe, inclusive, and welcoming environment for all. Below you can find a specific code of conduct for behavior in the lab, as well as a broader discussion of what constitutes an inclusive environment. For more information on professional conduct see the [MCW Policy on Professional Conduct](https://www.mcw.edu/about-mcw/non-discrimination-notice/mcw-professional-conduct-policy).

Please visit the Medical College of Wisconsin's website for the department of [diversity and inclusion](https://www.mcw.edu/departments/office-of-diversity-and-inclusion).

## Building an Inclusive Lab Environment

All members of the lab, along with visitors, are expected to agree to the following code of conduct. More information and training on respect in the workplace is available from MCW's [website](https://www1.mcw.edu/FileLibrary/Groups/FacultyAffairs/NewFacultyForms/NewFaculty-FacultyRespectTrain3.pdf). 

### Code of Conduct

The lab is dedicated to providing a harassment-free experience for everyone, regardless of gender, gender identity and expression, age, sexual orientation, disability, socioeconomic status, physical appearance, body size, race, national origin, or religion (or lack thereof). We do not tolerate harassment of lab members in any form.

All lab members will treat one another with respect and be sensitive to how one’s words and actions impact others. We do not tolerate the perpetuation of stereotypes; we do not tolerate other acts of microaggression ([more information](https://www.washington.edu/teaching/topics/inclusive-teaching/addressing-microaggressions-in-the-classroom/)). We are a team. We stand up for one another. We learn from each other. We hold each other accountable.

## Scientific Integrity

### Reproducible Research

I expect that all of our research will be, at minimum, reproducible (when possible, we will also test for replicability). As a researcher, it is your responsibility to ensure reproducibility of your research by: 1) detailed note-taking and 2) programming workflows with version control.

Programming workflows help with reproducibility because they take away choice and therefore variability. The ideal scenario is that we have a script or series of scripts that takes data from raw form to final product. Programming alone is not enough, though, because people can easily forget which script changes they made and when. Therefore, all projects that involve programming of any kind (so basically, all projects) must use some form of version control. I strongly recommend git in combination with GitHub (see below), unless you have a pre-existing workflow.

### Authorship

Authorship will be discussed prior to the beginning of a new project, so that expectations are clearly defined. If you feel that authorship was not adequately discussed, please raise your concerns and questions early and often. These decisions are made more difficult at the final stage of a project when we are ready to publish. However, changes to authorship may occur over the course of a project if a new person becomes involved or if someone is not fulfilling their planned role. In most cases, graduate students and postdocs will be a first author on publications on which they are the primary lead, and I will be a last/corresponding author. 

### Old Projects

For projects that required significant lab resources (e.g. large scale proteomics experiments): Project "ownership" expires 12 months after data collection has ended or whenever the original primary lead relinquishes their rights to the study, whichever comes first. At that point, I reserve the right to re-assign the project (or not) as needed to expedite publication. This policy is intended to avoid situations in which a dataset languishes for a long period of time, while still giving publication priority to the original primary lead.  I will never exclude you from participating, but decisions to change the lead are final and must be accepted. 
