# General Policies {#general}

## PI Availability
Until the pandemic ends, I will work from home a significant proportion of the time. After the pandemic, I expect to have times where my door is open, at which times you should feel free to come talk with me. Unless there is an emergency, if my door is closed, please send me an email or try back later instead of knocking. 

When working remotely, I am available over Teams or for ad-hoc meetings during regular office hours.


## Vacation
Everyone is allowed 15 days of vacation per year (3 work weeks). Please let me know at least 2 weeks in advance of your scheduled vacations.

## Meetings

### Lab Meetings & Journal Club
Weekly lab meetings will be focused on project presentations and going over new data/methods. Lab meetings will last 1.5 hours. If at the end of 1.5 hours, we need more time to discuss something, we will schedule another meeting. **All full-time lab members** including rotation students are expected to attend the weekly lab meeting. All part-time lab members (including undergraduates) are welcome to attend but attendance is not required.

In addition, we sometimes hold journal clubs in addition to lab meetings with research presentations. Journal clubs will focus on discussing new and/or important research articles. Some weeks, we'll discuss a single article that everyone has read; other weeks, we'll each read a paper on a specific theme and do mini-presentations on each paper. As with our internal lab meetings, all full-time lab members are expected to attend these additional meetings, and part-time lab members are invited but not required to attend.

During extended periods of working remotely, such as during the COVID-19 pandemic, we will also have regular lab “check-ins” (currently on a Tuesday-Thursday schedule) to set up our goals for the week, encourage casual interactions, etc.

### Individual Meetings

At the beginning of each semester, I will set a schedule to meet with each full-time lab member for one hour a week. If we do not have anything to discuss in a given week, that's is OK, we can just say hi or cancel it. Before each meeting, update your meeting agenda; this will also be a place where we document next steps. Over the summer, we may set the schedule on a weekly basis since summer schedules are more flexible and variable.

### Joint Lab Meetings

Occasionally we will participate in joint lab meetings, or join other labs for their lab meeting. As with our own meetings, be respectful, be supportive, and *be on time* at these meetings. The GS department is full of great colleagues and these meetings are an important opportunity for collaborative thinking and projects.

## Work Hours

One of the benefits of a career in academic research is that it is typically more flexible than other kinds of jobs. However, you should still treat it like a job. If you are employed for 40 hours a week, you should be working 40 hours a week. This applies to lab staff members and postdocs. You are not required to work over-time. For graduate students, I recognize that you have other demands on your time like classes and TA-ing but I still expect that you will be regularly engaged in your research.

Lab staff members are expected to keep regular hours (e.g., somewhere in the ballpark of 9-5). Graduate students and postdocs have more flexibility. However, in order to encourage lab interaction, I expect that all lab members will be in the lab (or available on Slack, when working remotely), at minimum, most weekdays between 11am and 4pm or so. If you’re going to be taking off from work on a normal workday (i.e., taking vacation or a personal or sick day), please let me know.

## Deadlines

If you need something from me by a particular deadline, please inform me as soon as you are aware of the deadline so that I can allocate my time as efficiently as possible. I will expect at least one week's notice, but I greatly prefer two weeks' notice. I will require two weeks' notice for letters of reference. If you do not adhere to these guidelines, I may not be able to meet your deadline. Please note that this applies to reading/ commenting on abstracts, papers, and manuscripts, in addition to filling out paperwork, etc. Reminder messages are appreciated as well!

## Presentations

I encourage you to seek out opportunities to present your research to the department, research community, or general public. If you are going to give a presentation (including posters and talks), be prepared to give a practice presentation to the lab at least one week ahead of time. Not only will this help you feel comfortable with the presentation, it will give you time to implement any feedback. I care about practice presentations because **a)** presenting your work is a huge part of being successful in science and it is important that you practice those skills as often as possible, and **b)** you are going to be representing not only yourself but also the rest of the lab.

There is a lab template for posters that you are free to modify as you see fit, but the header and general aesthetic should stay similar. If you have ideas for how to improve the poster template, please show the lab so we can decide whether to implement them as a group. This will help increase the visibility of our lab at conferences. There is no template for talks, and I encourage you to use your own style of presentation as long as it is polished and clear.

When making figures, it is helpful if you follow a few color-coding conventions, so that it’s easier to keep things consistent when I present your work in talks. For example, please use the viridis color scheme for heatmaps and any color mapping to esure visibility to color blind. There are also common figures and illustrations available. 

## Lab Travel

The lab will typically pay for full-time lab members to present their work at major conferences (e.g. ASMS, Keystone, HuPO). In general, the work should be "new" in that it has not been presented previously, and it should be appropriate for the conference. I expect to support your attendance to one conference per year. Meal costs and lodging will be reimbursed according to the MCW policy. The lab will also pay for new grad students and postdocs to attend one conference in their first year in lab (i.e. without presenting). If you wish to attend any other conference outside of these guidelines, come speak with me. If travel expenses are being paid off of a grant, additional restrictions may apply (come speak with me). These guidelines may change depending on the availability of funds. I recommend that lab members apply for other sources of funding available to them (e.g. departmental funds for grad students, ASMS travel awards).

## Letters of Reference/Recommendation

Letters of reference/recommendation are one of the many benefits of working in a research lab. I will write a letter for any student or lab member who has spent at least one year in the lab. Letters will be provided for shorter-term lab members in exceptional circumstances (e.g. new graduate students or postdocs applying for fellowships). I maintain this policy because I do not think that I can adequately evaluate someone who has been around for less than a year.
To request a letter of recommendation, please adhere to the deadline requirements described above. Send me your current CV and any relevant instructions for the contents of the letter. If you are applying for a grant, send me your specific aims or a short summary of the grant. In some but not all cases, I may ask you to draft a letter, which I will then revise to be consistent with my evaluation. This will ensure that I do not miss any details about your work that you think are relevant to the position you're applying for, and it will also help me complete the letter in a timely fashion. Please feel free to send me a reminder email close to the letter deadline.

## Funding

Funding for the lab comes from a variety of sources, including the lab startup fund, federal agencies (e.g. NIH), private foundations, and internal funds from the University of Washington. I will oversee all aspects of the financial management of our funding sources. However, it is important to me to be transparent about where research money comes from and how it's spent. Please ask if you want to know more details. In general, external funds tend to be restricted to expenses related to a particular project or set of projects, whereas some of the internal funds are flexible in that they can be used for any justifiable work-related purpose. 

All research funded by external grants must acknowledge the funding agency and grant number upon publication. 

## Safety

Part of maintaining a great working environment in the lab is maintaining safe working habits. For more information on safety in the lab check out these resources:

* [EHS Trainings](https://www.mcw.edu/departments/research-systems/training/safety)
* [Biosafety levels](https://www.mcw.edu/departments/institutional-biosafety-committee-ibc/biosafety-levels)
* [MCW safety manual](https://infoscope.mcw.edu/FileLibrary/Groups/InfoScopeSafety/Manuals/SafetyManual_2017.pdf)
