# Data and Instrumentation {#data}

## Instrumentation

We work with very expensive instrumentation that requires very expensive reagents and supplies. This secion give guidlines for the use of that instrumentation.

Instrumentation and equipment need to be maintained so that every member of the lab has access to complete their research projects. When you have finished using an instrument, you should leave it in a condition so that the next person who needs to use it does not need to fix/clean it. This essential to keeping the lab functioning efficiently.

### Mass spectrometers

Mass spectrometers (MSs) are the key technology we use to drive projects. Over the course of your work in the lab there will be opportunities to learn more about using, running and fixing the the MSs. I highly encourage you to learn as much as you can as well through the literature to understand what the instruments are capable of and not capable of.

If you run into issues in the operation of the instruments (including but not limited to hardware malfunctions or failures and software faults or errors), **alert me immediately**! These problems cannot be ignored and are more likely than not to cause considerable harm to the instrument if left unattended. Unaddressed issues are also likely to result in expensive instrument repairs (tens of thousands of dollars).

If you notice significant degradation of instrument performance during or after your runs, alert both Jesse and the next user so that samples are not lost!

**Before and after every scheduled use** you are requred to analyze a standard that captures the performance of the method you are using. You are responsible for returing the instrument to the next user in the same condition as you recieved it, and comparing the standard data before and after your analysis proves this. If you are doing nanoLC-MS/MS, then that standard should show the separation AND mass spectral quality and sensitivity. I will work with each of you to determine the best standard for your project. 


### HPLCs

Separation or enrichment of peptides, proteins, and small molecules using high performance liquid chromatography (HPLC) is an integral part of our workflows. HPLC systems are usually the main source of instrument problems. As with the mass spectrometers any issues with the hardware or software need to be addressed immediately.

## Data, Data, Data

### Scripts and Code

All scripts and code used for lab projects (including programs, websites, tools, data analysis work) should be deposited or version controlled in lab storage/servers. This includes depositing repositories in the lab GitHub. 

### Raw Data

Raw data will be backed up in at least two places to ensure that should it need to be accessed it can be. This is especially important for published data as someone may ask for these files years later. Unpublished data should be similarly managed to ensure that we do not need to revisit the same basic work again. If you are unsure or where to store your data contact Jesse!

**AS SOON AS YOU FINISH COLLECTING DATA FOR YOUR PROJECT** it should be uploaded to massive or a similar repository with metadata that describes the file naming convention. 

### Data sharing

Data for publication will be shared through PRIDE/ProteomeXchange or a similar repository. Sharing these data with the general community is essential for future development of MS methods.

### Lab Storage

We have a lab drive setup through the MCW research computing center. All data should be copied from the mass spectrometer as soon as it is collected and stored on our group drive.  


